/*
 * App Store Connect API
 *
 * The App Store Connect API is a REST API used to build custom workflows as part of your app development life cycle and automate actions you take in App Store Connect. Use of the API requires authorization via JSON Web Tokens (JWT); you obtain keys to create the tokens from your organization’s App Store Connect account. See Creating API Keys for App Store Connect API to create your keys and tokens.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package appstoreconnect
// AppAttributes struct for AppAttributes
type AppAttributes struct {
	// The bundle ID for your app. This ID must match the one you use in Xcode. The bundle ID cannot be changed after you upload your first build.
	BundleId string `json:"bundleId,omitempty"`
	// The name of your app as it will appear in the App Store. The maximum length is 30 characters.
	Name string `json:"name,omitempty"`
	// The primary locale for your app. If localized app information isn’t available in an App Store territory, the information from your primary language is used instead.
	PrimaryLocale string `json:"primaryLocale,omitempty"`
	// A unique ID for your app that is not visible on the App Store.
	Sky string `json:"sky,omitempty"`
}
