/*
 * App Store Connect API
 *
 * The App Store Connect API is a REST API used to build custom workflows as part of your app development life cycle and automate actions you take in App Store Connect. Use of the API requires authorization via JSON Web Tokens (JWT); you obtain keys to create the tokens from your organization’s App Store Connect account. See Creating API Keys for App Store Connect API to create your keys and tokens.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package appstoreconnect
// PagedDocumentLinks Links related to the response document, including paging links. All the response data constitutes a document.
type PagedDocumentLinks struct {
	// The link to the first page of documents.
	First string `json:"first,omitempty"`
	// The link to the next page of documents.
	Next string `json:"next,omitempty"`
	// (Required) The link that produced the current document.
	Self string `json:"self"`
}
