/*
 * App Store Connect API
 *
 * The App Store Connect API is a REST API used to build custom workflows as part of your app development life cycle and automate actions you take in App Store Connect. Use of the API requires authorization via JSON Web Tokens (JWT); you obtain keys to create the tokens from your organization’s App Store Connect account. See Creating API Keys for App Store Connect API to create your keys and tokens.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package appstoreconnect
import (
	"time"
)
// BetaGroupAttributes Attributes that describe a resource.
type BetaGroupAttributes struct {
	// A Boolean value that indicates whether the group is internal. Only existing users of App Store Connect may be added for internal beta testing.
	IsInternalGroup bool `json:"isInternalGroup,omitempty"`
	// The name for the beta group.
	Name string `json:"name,omitempty"`
	// The URL of the public link provided to your app's beta testers.
	PublicLink string `json:"publicLink,omitempty"`
	// A Boolean value that indicates whether a public link is enabled. Enabling a link allows you to invite anyone outside of your team to beta test your app. When you share this link, testers will be able to install the beta version of your app on their devices in TestFlight and share the link with others.
	PublicLinkEnabled bool `json:"publicLinkEnabled,omitempty"`
	// The ID as part of the URL of the public link.
	PublicLinkId string `json:"publicLinkId,omitempty"`
	// The maximum number of testers that can join this beta group using the public link. Values must be between 1 and 10,000.
	PublicLinkLimit int32 `json:"publicLinkLimit,omitempty"`
	// A Boolean value that limits the number of testers who can join the beta group using the public link.
	PublicLinkLimitEnabled bool `json:"publicLinkLimitEnabled,omitempty"`
	// The creation date of the beta group.
	CreatedDate time.Time `json:"createdDate,omitempty"`
}
