/*
 * App Store Connect API
 *
 * The App Store Connect API is a REST API used to build custom workflows as part of your app development life cycle and automate actions you take in App Store Connect. Use of the API requires authorization via JSON Web Tokens (JWT); you obtain keys to create the tokens from your organization’s App Store Connect account. See Creating API Keys for App Store Connect API to create your keys and tokens.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package appstoreconnect
// PagingInformationPage The paging information details.
type PagingInformationPage struct {
	// The total number of resources matching your request.
	Total int32 `json:"total,omitempty"`
	// The maximum number of resources to return per page, from 0 to 200.
	Limit int32 `json:"limit"`
}
